version: '3'

services:
  softether:
    build: softether
    network_mode: "host"
    privileged: true
    volumes:
      - softether_config:/vpnserver/config
    restart: always
  jupyter:
    build: jupyter
    ports:
      - "80:8888"
    volumes:
      - jupyter_data:/jupyter
    environment:
      - "VIRTUAL_HOST=kuwana.mynumber.dev"
      - "VIRTUAL_PORT=8888"
      - "LETSENCRYPT_HOST=kuwana.mynumber.dev"
    restart: always
volumes:
  jupyter_data:
  softether_config: