version: '2'

services:
  softether:
    build: softether
    network_mode: "host"
    privileged: true
  jupyter:
    build: jupyter
    ports:
      - "80:8888"
    environment:
      - "VIRTUAL_HOST=kuwana.mynumber.dev"
      - "VIRTUAL_PORT=8888"
      - "LETSENCRYPT_HOST=kuwana.mynumber.dev"